### ISSUE TITLE
Data for friction velocity and convection separately?

### ISSUE THREAD

**Issue by tomchor** [qingli411/LRF19_regime_diagram#1]
Hi, @qingli411, thanks very much for posting this online!

In addition to the data available here, I was interested in plotting the join PDF of  $u_\star$ and $w_\star$. Currently the data available is in the form of $h/L_L$ and $La_t$, so I can't extract $u_\star$ and $w_\star$ separately to make my plot. 

Do you by any chance have that data for $u_\star$ and $w_\star$ available to share? If so, I'd very much appreciate it!

Cheers

**Comment by qingli411** [comment]
Hi, @tomchor, thanks for your interest in using this! I just added the data for more parameters including $u_*$, surface buoyancy flux and boundary layer depth. Please see Cell 13 of the updated notebook.

**Comment by tomchor** [comment]
Hi, @qingli411 that's awesome! Thank you very much!
